# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.TextField(max_length=20)),
                ('name', models.TextField(default=' ')),
                ('sex', models.CharField(default='男', max_length=4)),
                ('classname', models.TextField(default=' ', null=True)),
                ('phone', models.CharField(max_length=13)),
                ('qq', models.CharField(max_length=15, null=True)),
                ('mail', models.TextField(null=True)),
                ('depart1', models.TextField(default=' ')),
                ('depart2', models.TextField(default=' ')),
                ('adjustment', models.BooleanField(default=True)),
                ('hobby', models.TextField(null=True)),
                ('experience', models.TextField(null=True)),
                ('judge', models.TextField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
